### ISSUE TITLE
Seam to do not work with GLPI 9.1.1

### ISSUE THREAD

**Issue by vlepetit** [InfotelGLPI/environment#3]
GLPI : 9.1.1
PLUGINS Environment : 2.0.0

Hi,

after install of environment 2.0.0 I do not have access to any of the subplugin like appliances.

If i go in administration > profils > environment with super-admin profil i just see one column "read" which is check for each line/subplugin. But i do not have column and checkbox for "create" or "update"  action.

What ca i do to have access to each sub plugin ?

Regards,
vlepetit

**Comment by amma35** [comment]
Hi,
The plugin takes over the rights of each plugin present in GLPI.

For example, for the Certificate submenu it is visible if the certificates plugin rights are enabled.

**Comment by vlepetit** [comment]
Hi,

Thanks for answers but , with your example, i can't see Certificate submenu while the read right is check in administration > profils > environment

Do i have to install each plugin separately, in addition to environment plugin ?

**Comment by amma35** [comment]
Yes, you have to install all the other plugins.

**Comment by vlepetit** [comment]
Ok

Now i understand :)

Thanks !
