### ISSUE TITLE
Don't leave me add new environment

### ISSUE THREAD

**Issue by gusfersa** [InfotelGLPI/environment#4]
For bug reports, you can open an issue here, provide us : 
- The version of the plugin ---> 2.0.0
- The version of your GLPI ---> 9.1.4
- The steps to reproduce your issue
---> Install and active plugin
---> Assets -> Environment -> Add button (Disabled)

**Comment by amma35** [comment]
It is not possible to add an environment.
This plugin enables you to group 7 plugins to one for more visibility of plugins menu. 
You must have one of its plugins:
        "appliances":https://forge.glpi-project.org/projects/show/appliances Plugin
        "webapplications":https://github.com/InfotelGLPI/webapplications Plugin
        "certificates":https://github.com/InfotelGLPI/certificates Plugin
        "accounts":https://github.com/InfotelGLPI/accounts Plugin
        "domains":https://forge.glpi-project.org/projects/show/domains Plugin
        "databases":https://github.com/InfotelGLPI/databases Plugin
        "badges":https://github.com/InfotelGLPI/badges Plugin
